export const instamartFields = [
    { api_name: "SUBJECT", display_label: "Subject" },
    { api_name: "QUERY_TIME", display_label: "Query Time" },
    { api_name: "QUERY_TYPE", display_label: "Query Type" },
    { api_name: "SENDER_CITY", display_label: "Sender City" },
    { api_name: "SENDER_NAME", display_label: "Sender Name" },
    { api_name: "SENDER_EMAIL", display_label: "Sender Email" },
    { api_name: "SENDER_PHONE", display_label: "Sender Phone" },
    { api_name: "SENDER_STATE", display_label: "Sender State" },
    { api_name: "CALL_DURATION", display_label: "Call Duration" },
    { api_name: "QUERY_MESSAGE", display_label: "Query Message" },
    { api_name: "SENDER_MOBILE", display_label: "Sender Mobile" },
    { api_name: "SENDER_ADDRESS", display_label: "Sender Address" },
    { api_name: "SENDER_COMPANY", display_label: "Sender Company" },
    { api_name: "SENDER_PINCODE", display_label: "Sender Pincode" },
    { api_name: "QUERY_MCAT_NAME", display_label: "Query MCAT Name" },
    { api_name: "RECEIVER_MOBILE", display_label: "Receiver Mobile" },
    { api_name: "UNIQUE_QUERY_ID", display_label: "Unique Query ID" },
    { api_name: "SENDER_EMAIL_ALT", display_label: "Sender Email (Alt)" },
    { api_name: "SENDER_PHONE_ALT", display_label: "Sender Phone (Alt)" },
    { api_name: "SENDER_MOBILE_ALT", display_label: "Sender Mobile (Alt)" },
    { api_name: "QUERY_PRODUCT_NAME", display_label: "Query Product Name" },
    { api_name: "SENDER_COUNTRY_ISO", display_label: "Sender Country ISO" },
  ];